/* tslint:disable */
import { ConfCliente } from './conf-cliente';
import { ConfContratoCliente } from './conf-contrato-cliente';
import { ConfProveedor } from './conf-proveedor';
import { Producto } from './producto';
export interface ConfiguracionAplicadaClienteObj {
  AgrupadorCaracteristica?: string;
  BasePrecioLista?: number;
  CAS?: string;
  CFT?: number;
  CVT?: number;
  CVU?: number;
  Catalogo?: string;
  ConfCliente?: ConfCliente;
  ConfContratoCliente?: ConfContratoCliente;
  ConfProveedor?: ConfProveedor;
  Control?: string;
  CostoFijoUnitario?: number;
  DescripcionProducto?: string;
  EnContrato?: boolean;
  FactorCostoFijo?: number;
  FrenteComercialUnitario?: number;
  IdAgrupadorCaracteristica?: string;
  IdCatIndustria?: string;
  IdCliente?: string;
  IdConfiguracionPrecioCliente?: string;
  IdConfiguracionPrecioProveedorFamilia?: string;
  IdContratoCliente?: string;
  IdContratoClienteMarcaConfiguracion?: string;
  IdFamilia?: string;
  IdMarca?: string;
  IdMarcaFamilia?: string;
  IdMarcaFamiliaCatIndustria?: string;
  IdProducto?: string;
  IdProveedor?: string;
  IdValorConfiguracionTiempoEntrega?: string;
  Importacion?: number;
  Industria?: string;
  MontoConceptoAA?: number;
  NivelConfiguracionProductoCliente?: string;
  NivelConfiguracionProductoContratoCliente?: string;
  NivelConfiguracionProductoProveedor?: string;
  NombreMarca?: string;
  NumPiezas?: number;
  PrecioLista?: number;
  PrecioProquifaNet?: number;
  PrecioTotal?: number;
  PrecioUnitario?: number;
  Producto?: Producto;
  Sector?: string;
  Subtipo?: string;
  TiempoEntrega?: string;
  Tipo?: string;
  Utilidad?: number;
  UtilidadTotal?: number;
  UtilidadUnitaria?: number;
  ValorEnAduana?: number;
  idCatSector?: string;
}
