/* tslint:disable */
import { ConfCliente } from './conf-cliente';
import { ConfProveedor } from './conf-proveedor';
export interface ConfiguracionAplicadaClientePrecioListaObj {
  BasePrecioLista?: number;
  CFT?: number;
  CVT?: number;
  CVU?: number;
  ClaveMonedaPagos?: string;
  ConfCliente?: ConfCliente;
  ConfProveedor?: ConfProveedor;
  Control?: string;
  CostoFijoUnitario?: number;
  CostoTotalIndicador?: number;
  FrenteComercialUnitario?: number;
  IdCatControl?: string;
  IdCatIndustria?: string;
  IdCatMonedaPagos?: string;
  IdCatMonedaVentas?: string;
  IdCatNivelIngreso?: string;
  IdCatSubtipoProducto?: string;
  IdCatTipoProducto?: string;
  IdCliente?: string;
  IdConfiguracionPrecioCliente?: string;
  IdConfiguracionPrecioProveedorFamilia?: string;
  IdFamilia?: string;
  IdMarcaFamilia?: string;
  IdMarcaFamiliaCatIndustria?: string;
  Importacion?: number;
  Industria?: string;
  MonedaVentaProveedor?: string;
  NivelConfiguracionProductoCliente?: string;
  NivelConfiguracionProductoProveedor?: string;
  NumPiezas?: number;
  PorcentajeRendimientoIndicador?: number;
  PorcentajeUtilidadIndicador?: number;
  PorcentajeUtilidadPrecioListaIndicador?: number;
  PrecioLista?: number;
  PrecioListaMonedaProveedor?: number;
  PrecioProquifaNet?: number;
  PrecioProquifaNetProveedor?: number;
  PrecioTotal?: number;
  PrecioUnitario?: number;
  Sector?: string;
  Subtipo?: string;
  Temporal?: boolean;
  Tipo?: string;
  TotalProducto?: number;
  UtilidadIndicador?: number;
  UtilidadPrecioListaIndicador?: number;
  UtilidadTotal?: number;
  UtilidadUnitaria?: number;
  ValorEnAduana?: number;
  idCatSector?: string;
}
