/* tslint:disable */
export interface FcppSeguimientoFacturaIndirecto {
  Actividad?: string;
  Activo?: boolean;
  Area?: string;
  ClabeInterbancaria?: string;
  Convenio?: boolean;
  Cuenta?: boolean;
  Descripcion?: string;
  FechaDeseadaDePago?: string;
  FechaRegistro?: string;
  FechaUltimaActualizacion?: string;
  IdArchivoPdf?: string;
  IdArchivoXml?: string;
  IdCatBanco?: string;
  IdCatMetodoDePagoCFDI?: string;
  IdCatMoneda?: string;
  IdCuentaContable?: string;
  IdFCPPSeguimientoFactura?: string;
  IdFCPPSeguimientoFacturaIndirecto?: string;
  MontoAPagar?: number;
  NumeroConvenio?: string;
  NumeroDeCuenta?: string;
  Pago?: boolean;
  Prepago?: boolean;
  Presupuesto?: string;
  RazonSocialEmisor?: string;
  RazonSocialReceptor?: string;
  Reembolso?: boolean;
  Referencia1?: string;
  Referencia2?: string;
  RfcEmisor?: string;
  RfcReceptor?: string;
  Sector?: string;
  Spei?: boolean;
  Sucursal?: string;
  Tarjeta?: boolean;
  TipoDeCosto?: string;
}
