/* tslint:disable */
import { PpPartidaPedido } from './pp-partida-pedido';
import { ValorConfiguracionTiempoEntrega } from './valor-configuracion-tiempo-entrega';
import { CatUnidadTiempo } from './cat-unidad-tiempo';
import { CotProductoOferta } from './cot-producto-oferta';
import { PpIncidenciaPartida } from './pp-incidencia-partida';
import { PpPartidaPedidoConfiguracion } from './pp-partida-pedido-configuracion';
import { VPartidaCotizacion } from './vpartida-cotizacion';
import { VProducto } from './vproducto';
export interface PpPartidaPedidoObj {
  Activo?: boolean;
  AplicaFleteExpress?: boolean;
  CantidadExistenteStock?: number;
  Comentarios?: string;
  CotizacionesVinculadas?: number;
  FechaCaducidadStock?: string;
  FechaEstimadaEntrega?: string;
  FechaRegistro?: string;
  FechaUltimaActualizacion?: string;
  GravaIVA?: boolean;
  IVA?: number;
  IdPPIncidenciaPartidaPedido?: string;
  IdPPPPartidaPedidoCorregida?: string;
  IdPPPartidaPedido?: string;
  IdPPPartidaPedidoConfiguracion?: string;
  IdPPPartidaPedidoMadre?: string;
  IdPPPedido?: string;
  IdPcPartidaPromesaDeCompra?: string;
  IdProducto?: string;
  IdValorConfiguracionTiempoEntrega?: string;
  ListaPPPartidaPedidoHijas?: Array<PpPartidaPedido>;
  Notas?: string;
  Numero?: number;
  NumeroDePiezas?: number;
  PorcentajeSobrePrecioLista?: number;
  PrecioFleteNoDesglosado?: number;
  PrecioFleteNoDesglosadoIVA?: number;
  PrecioUnitario?: number;
  Programada?: boolean;
  Subtotal?: number;
  TiempoEstimadoEntrega?: number;
  Total?: number;
  Tramitada?: boolean;
  Validada?: boolean;
  ValorConfiguracionTiempoEntrega?: ValorConfiguracionTiempoEntrega;
  catUnidadTiempo?: CatUnidadTiempo;
  cotProductoOferta?: CotProductoOferta;
  ppIncidenciaPartida?: PpIncidenciaPartida;
  ppPartidaPedidoConfiguracion?: PpPartidaPedidoConfiguracion;
  vPartidaCotizacion?: VPartidaCotizacion;
  vProducto?: VProducto;
}
