/* tslint:disable */
import { Flete } from './flete';
import { Lote } from './lote';
import { CotPartidaCotizacionDetalle } from './cot-partida-cotizacion-detalle';
import { PpIncidenciaPartida } from './pp-incidencia-partida';
import { PpPartidaPedidoAddendaSanofi } from './pp-partida-pedido-addenda-sanofi';
import { PpPartidaPedidoConfiguracion } from './pp-partida-pedido-configuracion';
import { PpPedidoFleteExpress } from './pp-pedido-flete-express';
export interface PretramitarPedidoPartidaObj {
  Activo?: boolean;
  AplicaFleteExpress?: boolean;
  CantidadExistenteStock?: number;
  Comentarios?: string;
  CotizacionesVinculadas?: number;
  FechaCaducidadStock?: string;
  FechaEstimadaEntrega?: string;
  FechaRegistro?: string;
  FechaUltimaActualizacion?: string;
  Flete?: Flete;
  GravaIVA?: boolean;
  IVA?: number;
  IdPPIncidenciaPartidaPedido?: string;
  IdPPPPartidaPedidoCorregida?: string;
  IdPPPartidaPedido?: string;
  IdPPPartidaPedidoConfiguracion?: string;
  IdPPPartidaPedidoMadre?: string;
  IdPPPedido?: string;
  IdPcPartidaPromesaDeCompra?: string;
  IdProducto?: string;
  IdValorConfiguracionTiempoEntrega?: string;
  Lote?: Lote;
  Notas?: string;
  Numero?: number;
  NumeroDePiezas?: number;
  PorcentajeSobrePrecioLista?: number;
  PrecioFleteNoDesglosado?: number;
  PrecioFleteNoDesglosadoIVA?: number;
  PrecioUnitario?: number;
  Programada?: boolean;
  Subtotal?: number;
  TiempoEstimadoEntrega?: number;
  Total?: number;
  Tramitada?: boolean;
  Validada?: boolean;
  cotPartidaCotizacionDetalle?: CotPartidaCotizacionDetalle;
  ppIncidenciaPartida?: PpIncidenciaPartida;
  ppPartidaPedidoAddendaSanofi?: PpPartidaPedidoAddendaSanofi;
  ppPartidaPedidoConfiguracion?: PpPartidaPedidoConfiguracion;
  ppPedidoFleteExpress?: PpPedidoFleteExpress;
}
