/* tslint:disable */
import { CalcularMontosImportacion } from './calcular-montos-importacion';
import { VOcPartidaDetalle } from './voc-partida-detalle';
export interface VGARProveedorOrdenDespachoDetalle {
  ATiempo?: boolean;
  Activo?: boolean;
  Aduana?: string;
  Bultos?: number;
  CalcularMontosImportacion?: CalcularMontosImportacion;
  FechaDeEntregaComprometida?: boolean;
  FechaEstimadaDeEntrega?: string;
  FechaHoraEstimadaArribo?: string;
  FechaHoraEstimadaSalidaAduana?: string;
  FechaRegistro?: string;
  FechaUltimaActualizacion?: string;
  Fletera?: string;
  Folio?: string;
  FueraDeTiempo?: boolean;
  GuiaDeEmbarque?: string;
  IdAduana?: string;
  IdAgenteAduanal?: string;
  IdArchivoCajaAbierta?: string;
  IdArchivoEvidencia?: string;
  IdArchivoPedimento?: string;
  IdCatFletera?: string;
  IdDireccionAduana?: string;
  IdEmpresaExportador?: string;
  IdEmpresaImportador?: string;
  IdImpOrdenDespacho?: string;
  IdProveedor?: string;
  IdUsuarioComprador?: string;
  Incoterm?: string;
  ListaVOcPartidaDetalle?: Array<VOcPartidaDetalle>;
  MontoTotalUSD?: number;
  NombreComercialAgenteAduanal?: string;
  NombreLegalAgenteAduanal?: string;
  NombreProveedor?: string;
  NumeroPedimento?: string;
  NumeroReferencia?: string;
  PackingListAmbos?: boolean;
  PackingListDetallado?: boolean;
  PackingListSimplificado?: boolean;
  PesoKg?: number;
  Piezas?: number;
  PrefijoEmpresaExportador?: string;
  PrefijoEmpresaImportador?: string;
  Programada?: boolean;
  RazonSocialEmpresaExportador?: string;
  RazonSocialEmpresaImportador?: string;
  TipoDeCambio?: number;
  UrgenteEnProgramacion?: boolean;
  UrgenteTiempo?: boolean;
}
