/* tslint:disable */
import { CalcularMontosImportacion } from './calcular-montos-importacion';
import { Empresa } from './empresa';
import { Lote } from './lote';
import { OcPartidaEdicionBackOrder } from './oc-partida-edicion-back-order';
import { OcPartidaEdicionConImpactoFEE } from './oc-partida-edicion-con-impacto-fee';
import { OcPartidaEdicionSinImpactoFEE } from './oc-partida-edicion-sin-impacto-fee';
import { VCatPais } from './vcat-pais';
import { OcPartida } from './oc-partida';
import { VImpCDPartidaProducto } from './vimp-cdpartida-producto';
import { OcPendienteCompraProducto } from './oc-pendiente-compra-producto';
import { VProducto } from './vproducto';
export interface VOcPartidaDetalle {
  A1Dia?: boolean;
  A2Dias?: boolean;
  A3Dias?: boolean;
  A7Dias?: boolean;
  AMasDe3Dias?: boolean;
  Activo?: boolean;
  CDBackOrder?: boolean;
  CDCancelar?: boolean;
  CDConfirmado?: boolean;
  CDResumen?: boolean;
  CalcularMontosImportacion?: CalcularMontosImportacion;
  Catalogo?: string;
  ClaveMoneda?: string;
  ConfiguracionPartidaEdicionBackOrder?: boolean;
  ConfiguracionPartidaEdicionConImpactoFEE?: boolean;
  ConfiguracionPartidaEdicionSinImpactoFEE?: boolean;
  Confirmada?: boolean;
  Descripcion?: string;
  EmpresaEmbarque?: Empresa;
  EstadoPartidaCompra?: boolean;
  EstadoPartidaEnInspeccion?: boolean;
  EstadoPartidaEnTransito?: boolean;
  EstadoPartidaEntregado?: boolean;
  EstadoPartidaPedido?: boolean;
  EstadoPartidaPorEmbalar?: boolean;
  FechaEstimadaDeArribo?: string;
  FechaEstimadaDeArriboOriginal?: string;
  FechaEstimadaEntrega?: string;
  FechaEstimadaEntregaPedido?: string;
  FleteExpress?: boolean;
  FolioPedidoInterno?: string;
  IdCatMoneda?: string;
  IdCliente?: string;
  IdFamilia?: string;
  IdImpListaArribo?: string;
  IdMarcaFamilia?: string;
  IdOcOrdenDeCompra?: string;
  IdOcPackingList?: string;
  IdOcPartida?: string;
  IdOcPendienteCompraProducto?: string;
  IdProducto?: string;
  IdProveedor?: string;
  Indice?: number;
  ListaLotes?: Array<Lote>;
  ListaOcPartidaEdicionBackOrder?: Array<OcPartidaEdicionBackOrder>;
  ListaOcPartidaEdicionConImpactoFEE?: Array<OcPartidaEdicionConImpactoFEE>;
  ListaOcPartidaEdicionSinImpactoFEE?: Array<OcPartidaEdicionSinImpactoFEE>;
  Moneda?: string;
  NombreCliente?: string;
  NombreProveedor?: string;
  NumeroDePiezas?: number;
  NumeroDePiezasStock?: number;
  NumeroOrdenDeCompra?: string;
  OrdenDeCompraConfirmada?: boolean;
  OrdenDeCompraEntregada?: boolean;
  OrdenDeCompraNoConfirmada?: boolean;
  PHS?: boolean;
  PackingListDeclarado?: boolean;
  PaisesOrdenLotes?: Array<VCatPais>;
  PartidaProgramada?: boolean;
  PartidaRegular?: boolean;
  PartidasMismoNumero?: Array<OcPartida>;
  PrecioLista?: number;
  PrecioListaUSD?: number;
  RazonSocialEmpresaCompra?: string;
  Stock?: boolean;
  SubIndice?: number;
  TotalPartida?: number;
  TotalUSD?: number;
  impCDOcPartidaObj?: VImpCDPartidaProducto;
  ocPartida?: OcPartida;
  ocPendienteCompraProducto?: OcPendienteCompraProducto;
  vProducto?: VProducto;
}
