/* tslint:disable */
import { RestriccionMensualDatosFacturacion } from './restriccion-mensual-datos-facturacion';
import { RestriccionTemporalDatosFacturacion } from './restriccion-temporal-datos-facturacion';
import { ValorConfiguracionTiempoEntrega } from './valor-configuracion-tiempo-entrega';
import { PpPartidaPedidoDetalle } from './pp-partida-pedido-detalle';
import { PpPedidoFleteExpress } from './pp-pedido-flete-express';
import { TpPartidaPedido } from './tp-partida-pedido';
import { TpPartidaPedidoAddendaSanofi } from './tp-partida-pedido-addenda-sanofi';
import { TpPedidoFleteExpress } from './tp-pedido-flete-express';
import { VLote } from './vlote';
import { VProducto } from './vproducto';
export interface VTramitarPedidoPartidaDetalle {
  Activo?: boolean;
  Catalogo?: string;
  ConIncidencias?: number;
  Control?: string;
  Controlado?: boolean;
  CotizacionVinculada?: number;
  CotizacionesVinculadas?: number;
  DeCatalogo?: boolean;
  Descripcion?: string;
  DiasEntrega?: number;
  EsIntervalo?: boolean;
  EstadoPartida?: string;
  FechaEstimadaEntrega?: string;
  IdCatControl?: string;
  IdCatProceso?: string;
  IdCatSubtipoProducto?: string;
  IdCatTipoProducto?: string;
  IdCatUnidadTiempo?: string;
  IdEmpresa?: string;
  IdProducto?: string;
  IdTPPartidaPedido?: string;
  IdTPPedido?: string;
  IdValorConfiguracionTiempoEntrega?: string;
  Monto?: number;
  MontoIVA?: number;
  MontoUSD?: number;
  NombreMarca?: string;
  NotasModificacion?: string;
  Numero?: number;
  NumeroDePiezas?: number;
  NumeroDePiezasStock?: number;
  PorcentajeSobrePrecioLista?: number;
  PrecioUnitario?: number;
  PrefijoEmpresa?: string;
  Programada?: boolean;
  RFC?: string;
  RazonSocialEmpresaFactura?: string;
  RestriccionMensualDatosFacturacion?: RestriccionMensualDatosFacturacion;
  RestriccionesTemporalesDatosFacturacion?: Array<RestriccionTemporalDatosFacturacion>;
  Subtipo?: string;
  TieneContrato?: boolean;
  TieneCotizacion?: boolean;
  TieneFleteExpress?: boolean;
  TieneIVA?: boolean;
  Tipo?: string;
  TipoPartidaCotizacion?: string;
  TipoPartidaTramitacion?: string;
  UnidadTiempo?: string;
  ValorConfiguracionTiempoEntrega?: ValorConfiguracionTiempoEntrega;
  ValorEsperado?: number;
  ValorMaximoIntervalo?: number;
  ValorMinimoIntervalo?: number;
  Vigente?: boolean;
  ppPartidaPedidoDetalle?: PpPartidaPedidoDetalle;
  ppPedidoFleteExpress?: PpPedidoFleteExpress;
  tpPartidaPedido?: TpPartidaPedido;
  tpPartidaPedidoAddendaSanofi?: TpPartidaPedidoAddendaSanofi;
  tpPedidoFleteExpress?: TpPedidoFleteExpress;
  vLote?: VLote;
  vProducto?: VProducto;
}
