/* tslint:disable */
import { TpPedidoComentariosAdicionales } from './tp-pedido-comentarios-adicionales';
import { ContactoDetalleObj } from './contacto-detalle-obj';
import { DatosFacturacionClienteDetalle } from './datos-facturacion-cliente-detalle';
import { DireccionClienteDetalle } from './direccion-cliente-detalle';
import { Empresa } from './empresa';
import { TupleTpPedidoContactoNotificadoEntregaContactoDetalleObj } from './tuple-tp-pedido-contacto-notificado-entrega-contacto-detalle-obj';
import { CatCondicionesDePago } from './cat-condiciones-de-pago';
import { CatDestino } from './cat-destino';
import { CatMetodoDePagoCFDI } from './cat-metodo-de-pago-cfdi';
import { CatMoneda } from './cat-moneda';
import { CatUsoCFDI } from './cat-uso-cfdi';
import { TpClienteCSCreditoMorosoCorreo } from './tp-cliente-cscredito-moroso-correo';
import { TpPedido } from './tp-pedido';
import { TpPedidoFleteExpressDetalle } from './tp-pedido-flete-express-detalle';
import { TpPedidoFleteUltimaMilla } from './tp-pedido-flete-ultima-milla';
import { TpSolicitudAutorizacionFinanzas } from './tp-solicitud-autorizacion-finanzas';
import { VCliente } from './vcliente';
export interface VTramitarPedidoDetalle {
  AlMenosMitadLineaDeCreditoVencida?: boolean;
  ClaveMoneda?: string;
  ComentariosAdicionales?: Array<TpPedidoComentariosAdicionales>;
  ConIncidencias?: number;
  ContactoDetalleObj?: ContactoDetalleObj;
  DatosFacturacionClienteDetallePorDefecto?: DatosFacturacionClienteDetalle;
  DireccionClienteDetalle?: DireccionClienteDetalle;
  EmpresaFactura?: Empresa;
  FacturasMorosas?: boolean;
  FechaEstimadaEntregaMax?: string;
  FechaLimiteEnvioOrdenDeCompra?: string;
  FechaRecepcion?: string;
  Finalizado?: boolean;
  FletesExpress?: number;
  IdArchivo?: string;
  IdCatMoneda?: string;
  IdCliente?: string;
  IdFlete?: string;
  IdTPPedido?: string;
  Liberado?: boolean;
  LineaDeCreditoMasSobreGiroVencidos?: boolean;
  LineaDeCreditoVencida?: boolean;
  ListaContactoNotificadoEntrega?: Array<TupleTpPedidoContactoNotificadoEntregaContactoDetalleObj>;
  NumeroOrdenDeCompra?: string;
  OcInterna?: boolean;
  OcInternaPediente?: boolean;
  Productos?: number;
  RequiereAutorizacionFinanzas?: boolean;
  SinOC?: boolean;
  Subtotal?: number;
  TieneFleteExpress?: boolean;
  Total?: number;
  TotalFletesMXN?: number;
  TotalFletesUSD?: number;
  TotalIVA?: number;
  TotalMXN?: number;
  TotalUSD?: number;
  Tramitado?: boolean;
  catCondicionesDePago?: CatCondicionesDePago;
  catDestino?: CatDestino;
  catMetodoDePagoCFDI?: CatMetodoDePagoCFDI;
  catMoneda?: CatMoneda;
  catUsoCFDI?: CatUsoCFDI;
  tpClienteCSCreditoMorosoCorreo?: TpClienteCSCreditoMorosoCorreo;
  tpPedido?: TpPedido;
  tpPedidoFleteExpressObj?: TpPedidoFleteExpressDetalle;
  tpPedidoFletesUltimaMilla?: Array<TpPedidoFleteUltimaMilla>;
  tpSolicitudAutorizacionFinanzas?: TpSolicitudAutorizacionFinanzas;
  vCliente?: VCliente;
}
