import {
  QueryResultConfiguracionPrecioProveedor,
  QueryResultConfiguracionPrecioProveedorFamilia,
  QueryResultConfiguracionPrecioUtilidadCategoriaProveedor,
  QueryResultConfiguracionProveedorFamiliaGeneral,
} from 'api-catalogos';

export interface GeneralConfiguration {
  ConfiguracionProveedorFamiliaGeneral: QueryResultConfiguracionProveedorFamiliaGeneral;
  ConfiguracionPrecioProveedorFamilia: QueryResultConfiguracionPrecioProveedorFamilia;
  ConfiguracionPrecioProveedor: QueryResultConfiguracionPrecioProveedor;
  ConfiguracionPrecioUtilidadCategoriaProveedor: QueryResultConfiguracionPrecioUtilidadCategoriaProveedor;
}
