import {Component} from '@angular/core';
import {Store} from '@ngrx/store';
import {AppState} from '@appCore/core.state';

@Component({
  selector: 'app-month',
  templateUrl: './month.component.html',
  styleUrls: ['./month.component.scss'],
})
export class MonthComponent {
  isOpen = false;

  itemsResults = [
    {
      Index: 1,
      fechaEntrega: new Date(),
      proveedor: 'Procter and Gamble Manufatura, S de R.L de C.V.',
      facturas: 15,
      cobroVencido: 5,
      pagar: '522222',
      pagado: '154121',
      recibido: true,
    },
    {
      Index: 2,
      fechaEntrega: new Date(),
      proveedor: 'Aspro',
      facturas: 15,
      cobroTiempo: 1,
      cobroVencido: 5,
      pagar: '522222',
      pagado: '154121',
      recibido: true,
    },
    {
      Index: 3,
      fechaEntrega: new Date(),
      proveedor: 'Aspro',
      facturas: 15,
      cobroTiempo: 1,
      cobroVencido: 5,
      pagar: '522222',
      pagado: '154121',
      recibido: false,
    },
    {
      Index: 4,
      fechaEntrega: new Date(),
      proveedor: 'Aspro',
      facturas: 15,
      cobroTiempo: 1,
      cobroVencido: 5,
      pagar: '522222',
      pagado: '154121',
      recibido: false,
    },
    {
      Index: 5,
      fechaEntrega: new Date(),
      proveedor: 'Aspro',
      facturas: 15,
      cobroTiempo: 1,
      pagar: '522222',
      pagado: '154121',
      recibido: false,
    },
    {
      Index: 1,
      fechaEntrega: new Date(),
      proveedor: 'Procter and Gamble Manufatura, S de R.L de C.V.',
      facturas: 15,
      cobroTiempo: 1,
      cobroVencido: 5,
      pagar: '522222',
      pagado: '154121',
      recibido: true,
    },
    {
      Index: 2,
      fechaEntrega: new Date(),
      proveedor: 'Aspro',
      facturas: 15,
      cobroTiempo: 1,
      pagar: '522222',
      pagado: '154121',
      recibido: true,
    },
    {
      Index: 3,
      fechaEntrega: new Date(),
      proveedor: 'Aspro',
      facturas: 15,
      cobroTiempo: 1,
      cobroVencido: 5,
      pagar: '522222',
      pagado: '154121',
      recibido: false,
    },
    {
      Index: 4,
      fechaEntrega: new Date(),
      proveedor: 'Aspro',
      facturas: 15,
      cobroTiempo: 1,
      cobroVencido: 5,
      pagar: '522222',
      pagado: '154121',
      recibido: false,
    },
    {
      Index: 5,
      fechaEntrega: new Date(),
      proveedor: 'Aspro',
      facturas: 15,
      cobroTiempo: 1,
      cobroVencido: 5,
      pagar: '522222',
      pagado: '154121',
      recibido: false,
    },
    {
      Index: 1,
      fechaEntrega: new Date(),
      proveedor: 'Procter and Gamble Manufatura, S de R.L de C.V.',
      facturas: 15,
      cobroTiempo: 1,
      cobroVencido: 5,
      pagar: '522222',
      pagado: '154121',
      recibido: true,
    },
    {
      Index: 2,
      fechaEntrega: new Date(),
      proveedor: 'Aspro',
      facturas: 15,
      cobroTiempo: 1,
      cobroVencido: 5,
      pagar: '522222',
      pagado: '154121',
      recibido: true,
    },
    {
      Index: 3,
      fechaEntrega: new Date(),
      proveedor: 'Aspro',
      facturas: 15,
      cobroTiempo: 1,
      cobroVencido: 5,
      pagar: '522222',
      pagado: '154121',
      recibido: false,
    },
    {
      Index: 4,
      fechaEntrega: new Date(),
      proveedor: 'Aspro',
      facturas: 15,
      cobroTiempo: 1,
      cobroVencido: 5,
      pagar: '522222',
      pagado: '154121',
      recibido: false,
    },
    {
      Index: 5,
      fechaEntrega: new Date(),
      proveedor: 'Aspro',
      facturas: 15,
      cobroTiempo: 1,
      cobroVencido: 5,
      pagar: '522222',
      pagado: '154121',
      recibido: false,
    },
    {
      Index: 1,
      fechaEntrega: new Date(),
      proveedor: 'Procter and Gamble Manufatura, S de R.L de C.V.',
      facturas: 15,
      cobroTiempo: 1,
      cobroVencido: 5,
      pagar: '522222',
      pagado: '154121',
      recibido: true,
    },
    {
      Index: 2,
      fechaEntrega: new Date(),
      proveedor: 'Aspro',
      facturas: 15,
      cobroTiempo: 1,
      cobroVencido: 5,
      pagar: '522222',
      pagado: '154121',
      recibido: true,
    },
    {
      Index: 3,
      fechaEntrega: new Date(),
      proveedor: 'Aspro',
      facturas: 15,
      cobroTiempo: 1,
      pagar: '522222',
      pagado: '154121',
      recibido: false,
    },
    {
      Index: 4,
      fechaEntrega: new Date(),
      proveedor: 'Aspro',
      facturas: 15,
      cobroTiempo: 1,
      cobroVencido: 5,
      pagar: '522222',
      pagado: '154121',
      recibido: false,
    },
    {
      Index: 5,
      fechaEntrega: new Date(),
      proveedor: 'Aspro',
      facturas: 15,
      cobroTiempo: 1,
      cobroVencido: 5,
      pagar: '522222',
      pagado: '154121',
      recibido: false,
    },
  ];

  constructor(private store: Store<AppState>) {}

  onClick(): void {
    if (this.isOpen === true) {
      this.isOpen = false;
    } else {
      this.isOpen = true;
    }
  }
}
