import * as importProviderSelectors from '@appSelectors/forms/providers/providers.selectors';
import * as importListProviderSelectors from '@appSelectors/forms/providers/providers-list/providers-list.selectors';
import * as importAddEditProviderSelectors from '@appSelectors/forms/providers/providers-details/providers-details.selectors';
import * as importGeneralDataProviderSelectors from '@appSelectors/forms/providers/providers-details/provider-form-step-1-general-data.selectors';
import * as importTrademarksProviderSelectors from '@appSelectors/forms/providers/providers-details/provider-form-step-4-trademark.selectors';
import * as importCampaignsProviderSelectors from '@appSelectors/forms/providers/providers-details/provider-form-step-3-campaign.selectors';
import * as importLogisticsAndPaymentSelectors from '@appSelectors/forms/providers/providers-details/provider-form-step-5-logistics-and-payments.selectors';
import * as importBuySaleProviderSelectors from '@appSelectors/forms/providers/providers-details/provider-form-step-6-buy-sale-and-licences.selectors';
import * as importOfferSelectors from '@appSelectors/forms/providers/providers-details/provider-form-step-8-offer.selectors';
import * as importClassificationSelectors from '@appSelectors/forms/providers/providers-details/provider-form-step-7-classification.selectors';

export const providerSelectors = importProviderSelectors;
export const providerListSelectors = importListProviderSelectors;
export const providersDetailsSelectors = importAddEditProviderSelectors;
export const generalDataProviderSelectors = importGeneralDataProviderSelectors;
export const trademarkProviderSelectors = importTrademarksProviderSelectors;
export const campaignsProviderSelectors = importCampaignsProviderSelectors;
export const logisticsAndPaymentsSelectors = importLogisticsAndPaymentSelectors;
export const buySaleProviderSelectors = importBuySaleProviderSelectors;
export const offerSelectors = importOfferSelectors;
export const classificationSelectors = importClassificationSelectors;
